program: /home/elicer/BookGNN/src/training.py
project: Prometheus-GNN-Book-Recommendations
method: random # bayes, grid
metric:
  name: val_recall
  goal: maximize
parameters:
  conv_layer:
    values: ['LGC']
  epochs:
    values: [150]
  num_layers:
    values: [3, 4, 5]
  lr:
    min: 0.0001
    max: 0.001
  neg_samp:
    values: ['random', 'hard']
  emb_size:
    values: [32, 64, 128]
  weight_decay:
    values: [1e-5, 1e-4, 1e-3]
  gat_dropout:
    min: 0.1
    max: 0.5
  gat_n_heads:
    values: [1, 2, 4, 5]
